# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuardioesApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GuardioesApp
  pod 'FacebookSDK'
  
  target 'GuardioesApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuardioesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GuardioesApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
